language: php
services:
  - redis-server
  - mysql
php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - PLUGIN_NAME=RedisCache
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.10

matrix:
  include:
    - php: 7.2
      env:
        - DB=mysql
        - CAKE_VERSION=2.10
        - CODECOVERAGE=1
    - php: 7.1
      env:
        - PHPCS=1

before_script:
  - git clone -b master https://github.com/peloncano/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ls -la
  - ls -la ..
  - ls -la ../..
  - cat ../cakephp/app/Config/bootstrap.php
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
